version: '3.8'

services:
  shr-mediator:
    command: ["npm", "run", "start:dev"]
    # entrypoint: node --inspect=0.0.0.0:9230 /app/dist/app.js
    ports:
      - target: 9230
        published: 9230
        mode: host
      - target: 3000
        published: 3004
        mode: host
      - target: 3001
        published: 3001
        mode: host
      - target: 3002
        published: 3002
        mode: host
