version: '3.8'

services:
  shr-mediator:
    image: jembi/shr-mediator:local
    networks:
      - default
      - hapi-fhir
      - shr
      - kafka
      - opencr
      - openhim
      - converter
    environment:
      HTTP_PORT: ${SHR_HTTP_PORT}
      SHR_MLLP_PORT: ${SHR_MLLP_PORT}
      SHR_MLLP_ORU_PORT: ${SHR_MLLP_ORU_PORT}
      CR_MEDIATOR_API_URL: ${SHR_CR_MEDIATOR_API_URL}
      CR_MEDIATOR_API_USERNAME: ${SHR_CR_MEDIATOR_API_USERNAME}
      CR_MEDIATOR_API_PASSWORD: ${SHR_CR_MEDIATOR_API_PASSWORD}
      OMANG_SYSTEM: ${SHR_OMANG_SYSTEM}
      BDRS_SYSTEM: ${SHR_BDRS_SYSTEM}
      IMMIGRATION_SYSTEM: ${SHR_IMMIGRATION_SYSTEM}
      DEV_MODE: ${SHR_DEV_MODE}
      FHIR_SERVER_BASE_URL: ${SHR_FHIR_SERVER_BASE_URL}
      FHIR_SERVER_USERNAME: ${SHR_FHIR_SERVER_USERNAME}
      FHIR_SERVER_PASSWORD: ${SHR_FHIR_SERVER_PASSWORD}
      FHIR_CONVERTER_URL: ${SHR_FHIR_CONVERTER_URL}
      BROKERS: ${SHR_TASK_RUNNER_BROKERS}
      TRANSLATOR_MAX_RETRIES: ${SHR_RETRY_CONFIG_TRANSLATOR_MAX_RETRIES}
      TRANSLATOR_RETRY_DELAY: ${SHR_RETRY_CONFIG_TRANSLATOR_RETRY_DELAY}
      HL7_MAX_RETRIES: ${SHR_RETRY_CONFIG_HL7_MAX_RETRIES}
      HL7_RETRY_DELAY: ${SHR_RETRY_CONFIG_HL7_RETRY_DELAY}
      KAFKA_MAX_RETRIES: ${SHR_RETRY_CONFIG_KAFKA_MAX_RETRIES}
      KAFKA_RETRY_DELAY: ${SHR_RETRY_CONFIG_KAFKA_RETRY_DELAY}
      PIMS_SYSTEM_URL: ${SHR_BW_CONFIG_PIMS_SYSTEM_URL}
      IPMS_SYSTEM_URL: ${SHR_BW_CONFIG_IPMS_SYSTEM_URL}
      CIEL_SYSTEM_URL: ${SHR_BW_CONFIG_CIEL_SYSTEM_URL}
      LOINC_SYSTEM_URL: ${SHR_BW_CONFIG_LOINC_SYSTEM_URL}
      OMANG_SYSTEM_URL: ${SHR_OMANG_SYSTEM}
      BDRS_SYSTEM_URL: ${SHR_BDRS_SYSTEM}
      LAB_ORDER_SYSTEM_URL: ${SHR_BW_CONFIG_LAB_ORDER_SYSTEM_URL}
      MRN_SYSTEM_URL: ${SHR_BW_CONFIG_MRN_SYSTEM_URL}
      IMMIGRATION_SYSTEM_URL: ${SHR_IMMIGRATION_SYSTEM}
      OCL_URL: ${SHR_BW_CONFIG_OCL_URL}
      FACILITY_CODE_SYSTEM_URL: ${SHR_BW_CONFIG_FACILITY_CODE_SYSTEM_URL}
      IPMS_PROVIDER_SYSTEM_URL: ${SHR_BW_CONFIG_IPMS_PROVIDER_SYSTEM_URL}
      IPMS_PATIENT_TYPE_SYSTEM_URL: ${SHR_BW_CONFIG_IPMS_PATIENT_TYPE_SYSTEM_URL}
      IPMS_PATIENT_STATUS_SYSTEM_URL: ${SHR_BW_CONFIG_IPMS_PATIENT_STATUS_SYSTEM_URL}
      IPMS_X_LOCATION_SYSTEM_URL: ${SHR_BW_CONFIG_IPMS_X_LOCATION_SYSTEM_URL}
      IPMS_ORDER_TYPE_SYSTEM_URL: ${SHR_BW_CONFIG_IPMS_ORDER_TYPE_SYSTEM_URL}
      REQUEST_TIMEOUT: ${SHR_BW_CONFIG_REQUEST_TIMEOUT}
      TO_IPMS_ADT_TEMPLATE: ${SHR_BW_CONFIG_TO_IPMS_ADT_TEMPLATE}
      FROM_IPMS_ADT_TEMPLATE: ${SHR_BW_CONFIG_FROM_IPMS_ADT_TEMPLATE}
      TO_IPMS_ORM_TEMPLATE: ${SHR_BW_CONFIG_TO_IPMS_ORM_TEMPLATE}
      FROM_IPMS_ORU_TEMPLATE: ${SHR_BW_CONFIG_FROM_IPMS_ORU_TEMPLATE}
      MLLP_TARGET_HOST: ${SHR_BW_CONFIG_MLLP_TARGET_HOST}
      MLLP_TARGET_ADT_PORT: ${SHR_BW_CONFIG_MLLP_TARGET_ADT_PORT}
      MLLP_TARGET_ORM_PORT: ${SHR_BW_CONFIG_MLLP_TARGET_ORM_PORT}
      LOGGER_MAX_LOG_SIZE: ${SHR_LOGGER_MAX_LOG_SIZE}
      LOGGER_MAX_NUM_OF_LOGS: ${SHR_LOGGER_MAX_NUM_OF_LOGS}
      OPENHIM_AUTH_USERNAME: ${SHR_OPENHIM_USERNAME}
      OPENHIM_AUTH_PASSWORD: ${SHR_OPENHIM_PASSWORD}
      OPENHIM_AUTH_TRUST_SELF_SIGNED: ${SHR_OPENHIM_TRUST_SELF_SIGNED}
      OPENHIM_AUTH_API_URL: ${SHR_MEDIATOR_CONFIG_OPENHIM_AUTH_API_URL}
      OPENHIM_AUTH_REJECT_UNAUTHORIZED: ${SHR_MEDIATOR_CONFIG_OPENHIM_AUTH_REJECT_UNAUTHORIZED}
      OPENHIM_AUTH_URN: ${SHR_MEDIATOR_CONFIG_OPENHIM_AUTH_URN}
      MEDIATOR_CORE_HOST: ${SHR_MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_CORE_HOST}
      MEDIATOR_REGISTER_MEDIATOR_PATH: ${SHR_MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_REGISTER_MEDIATOR_PATH}
      MEDIATOR_HEARTBEAT_PATH: ${SHR_MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_HEARTBEAT_PATH}
      MEDIATOR_HEARTBEAT_INTERVAL: ${SHR_MEDIATOR_CONFIG_MEDIATOR_CORE_HEARTBEAT_INTERVAL}
      MEDIATOR_HEARTBEAT_DISABLED: ${SHR_MEDIATOR_CONFIG_MEDIATOR_CORE_IS_HEARTBEAT_DISABLED}
      MEDIATOR_SETUP_URN: ${SHR_MEDIATOR_CONFIG_MEDIATOR_SETUP_URN}
      MEDIATOR_SETUP_VERSION: ${SHR_MEDIATOR_CONFIG_MEDIATOR_SETUP_VERSION}
      MEDIATOR_SETUP_NAME: ${SHR_MEDIATOR_CONFIG_MEDIATOR_SETUP_NAME}
      MEDIATOR_SETUP_DESCRIPTION: ${SHR_MEDIATOR_CONFIG_MEDIATOR_SETUP_DESCRIPTION}
    configs:
      - target: /app/src/botswana/ocl_json/IPMSLAB_to_CIEL.json
        source: IPMSLAB_to_CIEL.json
      - target: /app/src/botswana/ocl_json/IPMSLAB_to_PIMSLAB.json
        source: IPMSLAB_to_PIMSLAB.json
      - target: /app/src/botswana/ocl_json/PIMSLAB_to_CIEL.json
        source: PIMSLAB_to_CIEL.json
      - target: /app/src/botswana/ocl_json/PIMSLAB_to_IPMSLAB.json
        source: PIMSLAB_to_IPMSLAB.json
      - target: /app/src/botswana/ocl_json/IPMS_Coding.json
        source: IPMS_Coding.json
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

configs:
  IPMSLAB_to_CIEL.json:
    file: ./config/ocl_json/IPMSLAB_to_CIEL.json
    name: IPMSLAB_to_CIEL.json-${IPMSLAB_to_CIEL_json_DIGEST:?err}
    labels:
      name: shr-mediator
  IPMSLAB_to_PIMSLAB.json:
    file: ./config/ocl_json/IPMSLAB_to_PIMSLAB.json
    name: IPMSLAB_to_PIMSLAB.json-${IPMSLAB_to_PIMSLAB_json_DIGEST:?err}
    labels:
      name: shr-mediator
  PIMSLAB_to_CIEL.json:
    file: ./config/ocl_json/PIMSLAB_to_CIEL.json
    name: PIMSLAB_to_CIEL.json-${PIMSLAB_to_CIEL_json_DIGEST:?err}
    labels:
      name: shr-mediator
  PIMSLAB_to_IPMSLAB.json:
    file: ./config/ocl_json/PIMSLAB_to_IPMSLAB.json
    name: PIMSLAB_to_IPMSLAB.json-${PIMSLAB_to_IPMSLAB_json_DIGEST:?err}
    labels:
      name: shr-mediator
  IPMS_Coding.json:
    file: ./config/ocl_json/IPMS_Coding.json
    name: IPMS_Coding.json-${IPMS_Coding_json_DIGEST:?err}
    labels:
      name: shr-mediator


networks:
  default:
  kafka:
    name: kafka_public
    external: true
  hapi-fhir:
    name: hapi-fhir_public
    external: true
  shr:
    name: shr_public
    external: true
    attachable: true
  opencr:
    name: opencr_public
    external: true
  openhim:
    name: openhim_public
    external: true
  converter:
    name: converter_public
    external: true
