version: "3.8"

services:
  omang-api:
    image: jembi/omangsvc:local
    networks:
      opencr:
      hapi-fhir:
      elasticsearch:
      default:
      openhim:
      public:
    environment:
      - CLIENT_REGISTRY_API_URL=${OMANG_CLIENT_REGISTRY_API_URL}
      - CLIENT_REGISTRY_OMANG_SYSTEM=${OMANG_CLIENT_REGISTRY_OMANG_SYSTEM}
      - CLIENT_REGISTRY_BDRS_SYSTEM=${OMANG_CLIENT_REGISTRY_BDRS_SYSTEM}
      - CLIENT_REGISTRY_IMMIGRATION_SYSTEM=${OMANG_CLIENT_REGISTRY_IMMIGRATION_SYSTEM}
      - CLIENT_REGISTRY_MAX_DAYS_BEFORE_UPDATE=${OMANG_CLIENT_REGISTRY_MAX_DAYS_BEFORE_UPDATE}
      - CLIENT_REGISTRY_DEV_MODE=${OMANG_CLIENT_REGISTRY_DEV_MODE}
      - LOGGER_MAX_LOG_SIZE=${OMANG_LOGGER_MAX_LOG_SIZE}
      - LOGGER_MAX_NUM_OF_LOGS=${OMANG_LOGGER_MAX_NUM_OF_LOGS}
      - AUTH_BASIC_ID=${OMANG_AUTH_BASIC_ID}
      - AUTH_BASIC_USERNAME=${OMANG_AUTH_BASIC_USERNAME}
      - AUTH_BASIC_PASSWORD=${OMANG_AUTH_BASIC_PASSWORD}
      - SAFE_LIST_IP=${OMANG_SAFE_LIST_IP}
      - ORACLE_OMANG_CITIZEN_CONNECTION_STRING=${OMANG_ORACLE_CITIZEN_CONNECTION_STRING}
      - ORACLE_OMANG_VIEW_NAME=${OMANG_ORACLE_OMANG_VIEW_NAME}
      - ORACLE_OMANG_CITIZEN_USERNAME=${OMANG_ORACLE_CITIZEN_USERNAME}
      - ORACLE_OMANG_CITIZEN_PASSWORD=${OMANG_ORACLE_CITIZEN_PASSWORD}
      - ORACLE_IMMIGRATION_CONNECTION_STRING=${OMANG_ORACLE_IMMIGRATION_CONNECTION_STRING}
      - ORACLE_IMMIGRATION_VIEW_NAME=${OMANG_ORACLE_IMMIGRATION_VIEW_NAME}
      - ORACLE_IMMIGRATION_USERNAME=${OMANG_ORACLE_IMMIGRATION_USERNAME}
      - ORACLE_IMMIGRATION_PASSWORD=${OMANG_ORACLE_IMMIGRATION_PASSWORD}
      - ORACLE_BDRS_CONNECTION_STRING=${OMANG_ORACLE_BDRS_CONNECTION_STRING}
      - ORACLE_BIRTHS_VIEW_NAME=${OMANG_ORACLE_BIRTHS_VIEW_NAME}
      - ORACLE_BDRS_USERNAME=${OMANG_ORACLE_BDRS_USERNAME}
      - ORACLE_BDRS_PASSWORD=${OMANG_ORACLE_BDRS_PASSWORD}
      - ORACLE_DEATHS_VIEW_NAME=${OMANG_ORACLE_DEATHS_VIEW_NAME}
      - OPENHIM_AUTH_USERNAME=${OMANG_OPENHIM_AUTH_USERNAME}
      - OPENHIM_AUTH_PASSWORD=${OMANG_OPENHIM_AUTH_PASSWORD}
      - OPENHIM_AUTH_TRUST_SELF_SIGNED=${OMANG_OPENHIM_AUTH_TRUST_SELF_SIGNED}
      - OPENHIM_AUTH_API_URL=${OMANG_OPENHIM_AUTH_API_URL}
      - OPENHIM_AUTH_REJECT_UNAUTHORIZED=${OMANG_OPENHIM_AUTH_REJECT_UNAUTHORIZED}
      - OPENHIM_AUTH_URN=${OMANG_OPENHIM_AUTH_URN}
      - MEDIATOR_CORE_OPENHIM_CORE_HOST=${OMANG_MEDIATOR_CORE_OPENHIM_CORE_HOST}
      - MEDIATOR_CORE_OPENHIM_REGISTER_MEDIATOR_PATH=${OMANG_MEDIATOR_CORE_OPENHIM_REGISTER_MEDIATOR_PATH}
      - MEDIATOR_CORE_OPENHIM_HEARTBEAT_PATH=${OMANG_MEDIATOR_CORE_OPENHIM_HEARTBEAT_PATH}
      - MEDIATOR_CORE_HEARTBEAT_INTERVAL=${OMANG_MEDIATOR_CORE_HEARTBEAT_INTERVAL}
      - MEDIATOR_CORE_IS_HEARTBEAT_DISABLED=${OMANG_MEDIATOR_CORE_IS_HEARTBEAT_DISABLED}
      - MEDIATOR_SETUP_URN=${OMANG_MEDIATOR_SETUP_URN}
      - MEDIATOR_SETUP_VERSION=${OMANG_MEDIATOR_SETUP_VERSION}
      - MEDIATOR_SETUP_NAME=${OMANG_MEDIATOR_SETUP_NAME}
      - MEDIATOR_SETUP_DESCRIPTION=${OMANG_MEDIATOR_SETUP_DESCRIPTION}
      - ORACLE_DB_HOST=${OMANG_ORACLE_DB_HOST}
      - ORACLE_DB_SID=${OMANG_ORACLE_DB_SID}
      - ORACLE_DB_PORT=${OMANG_ORACLE_DB_PORT}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  opencr:
    name: opencr_public
    external: true
  hapi-fhir:
    name: hapi-fhir_public
    external: true
  elasticsearch:
    name: elastic_public
    external: true
  openhim:
    name: openhim_public
    external: true
  default:
  public:
    name: omang-api_public
    external: true
