version: "3.8"

services:
  oracle-db:
    image: ${OMANG_ORACLE_DOCKER_IMAGE}
    environment:
      - ORACLE_SID=${OMANG_ORACLE_SID}
      - ORACLE_ALLOW_REMOTE=true
      - TZ=GMT
      - ORACLE_PASSWORD=${OMANG_ORACLE_PASSWORD}
    configs:
      - source: init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      public:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
    ports:
      - target: 1521
        published: 1522
        mode: host

  omang-api:
    ports:
      - target: 80
        published: 8098
        mode: host
    volumes:
      - ${OMANG_DEV_MOUNT_FOLDER}/src:/app/src
      - ${OMANG_DEV_MOUNT_FOLDER}/node_modules:/app/node_modules
    command: ["npm", "run", "start:dev"]

configs:
  init_sql:
    file: ./config/init.sql
    name: init.sql
    labels:
      name: oracle
