version: "3.8"

services:
  oracle-db:
    image: ${OMANG_ORACLE_DOCKER_IMAGE}
    environment:
      - ORACLE_SID=${OMANG_ORACLE_SID}
      - ORACLE_ALLOW_REMOTE=true
      - TZ=GMT
      - ORACLE_PASSWORD=${OMANG_ORACLE_PASSWORD}
    configs:
      - source: init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      public:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
    ports:
      - "1521:1522"

  omang-api:
    ports:
      - 5002:80
    volumes:
      - ${OMANG_DEV_MOUNT_FOLDER}/src:/app/src
      - ${OMANG_DEV_MOUNT_FOLDER}/node_modules:/app/node_modules

configs:
  init_sql:
    file: ./config/init.sql
    name: init.sql-test1234
    labels:
      name: oracle
