version: "3.8"

services:
  omang-api:
    ports:
      - 5002:80
    volumes:
      - ../projects/omang-service-mediator/src:/app/src
      - ../projects/omang-service-mediator/node_modules:/app/node_modules
    depends_on:
      oracle-db:
        condition: service_healthy
  
  oracle-db:
    image: gvenzl/oracle-xe
    hostname: oracle-db
    container_name: oracle-db
    restart: always
    environment:
    - ORACLE_SID=XE 
    - ORACLE_ALLOW_REMOTE=true
    - TZ=GMT
    - ORACLE_RANDOM_PASSWORD=yes
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - omangsvc
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s SYSTEM/oracle@//localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 10
