projectName: platform
image: jembi/platform:latest
logPath: /tmp/logs

packages:
  - interoperability-layer-openhim
  - reverse-proxy-nginx
  - fhir-datastore-hapi-fhir
  - monitoring
  - database-postgres
  - identity-access-manager-keycloak
  - client-registry-opencr
  - analytics-datastore-elastic-search
  - message-bus-kafka

profiles:
  - name: dev
    packages:
      - interoperability-layer-openhim
      - database-postgres
      - fhir-datastore-hapi-fhir
      - monitoring
      - identity-access-manager-keycloak
      - client-registry-opencr
      - analytics-datastore-elastic-search
      - message-bus-kafka
    envFiles:
      - .env.local
    dev: true
    only: false
