projectName: platform
image: jembi/platform:latest
logPath: /tmp/logs

packages:
  - interoperability-layer-openhim
  - reverse-proxy-nginx
  - fhir-datastore-hapi-fhir
  - monitoring
  - database-postgres
  - identity-access-manager-keycloak
  - client-registry-opencr
  - analytics-datastore-elastic-search
  - message-bus-kafka
  - omang-service-mediator
  - openhim-mediator-fhir-converter
  - shr-mediator
  - dashboard-visualiser-kibana
  - fhir-ig-importer
  - facility-registry-mfl

profiles:
  - name: dev
    packages:
      - interoperability-layer-openhim
      - database-postgres
      - fhir-datastore-hapi-fhir
      - monitoring
      - identity-access-manager-keycloak
      - client-registry-opencr
      - analytics-datastore-elastic-search
      - message-bus-kafka
      - omang-service-mediator
      - openhim-mediator-fhir-converter
      - shr-mediator
      - dashboard-visualiser-kibana
      - fhir-ig-importer
      - facility-registry-mfl
    envFiles:
      - .env.local
    dev: true
    only: false

  - name: qa
    packages:
      - reverse-proxy-nginx
      - interoperability-layer-openhim
      - database-postgres
      - fhir-datastore-hapi-fhir
      - monitoring
      - identity-access-manager-keycloak
      - client-registry-opencr
      - analytics-datastore-elastic-search
      - message-bus-kafka
      - omang-service-mediator
      - openhim-mediator-fhir-converter
      - shr-mediator
      - fhir-ig-importer
      - facility-registry-mfl
    envFiles:
      - .env.qa
    dev: true
    only: false

  - name: pilot
    packages:
      - reverse-proxy-nginx
      - interoperability-layer-openhim
      - database-postgres
      - fhir-datastore-hapi-fhir
      - monitoring
      - identity-access-manager-keycloak
      - client-registry-opencr
      - analytics-datastore-elastic-search
      - message-bus-kafka
      - omang-service-mediator
      - openhim-mediator-fhir-converter
      - shr-mediator
      - fhir-ig-importer
      - facility-registry-mfl
    envFiles:
      - .env.pilot
    dev: true
    only: false

  - name: uat
    packages:
      - reverse-proxy-nginx
      - interoperability-layer-openhim
      - database-postgres
      - fhir-datastore-hapi-fhir
      - monitoring
      - identity-access-manager-keycloak
      - client-registry-opencr
      - analytics-datastore-elastic-search
      - message-bus-kafka
      - omang-service-mediator
      - openhim-mediator-fhir-converter
      - shr-mediator
      - fhir-ig-importer
      - facility-registry-mfl
    envFiles:
      - .env.uat
    dev: false
    only: false

  - name: prod
    packages:
      - reverse-proxy-nginx
      - interoperability-layer-openhim
      - database-postgres
      - fhir-datastore-hapi-fhir
      - monitoring
      - identity-access-manager-keycloak
      - client-registry-opencr
      - analytics-datastore-elastic-search
      - message-bus-kafka
      - omang-service-mediator
      - openhim-mediator-fhir-converter
      - shr-mediator
      - fhir-ig-importer
      - facility-registry-mfl
    envFiles:
      - .env.prod
    dev: false
    only: false
