version: "3.8"

services:
  mfl-api:
    image: jembi/mflsvc:local
    networks:
      openhim:
      default:
      public:
    environment:
      - HTTP_PORT=${MFL_HTTP_PORT}
      - DEV_MODE=${MFL_DEV_MODE}
      - LOGGER_MAX_LOG_SIZE=${MFL_LOGGER_MAX_LOG_SIZE}
      - LOGGER_MAX_NUM_OF_LOGS=${MFL_LOGGER_MAX_NUM_OF_LOGS}
      - OPENHIM_USERNAME=${MFL_OPENHIM_USERNAME}
      - OPENHIM_PASSWORD=${MFL_OPENHIM_PASSWORD}
      - OPENHIM_TRUST_SELF_SIGNED=${MFL_OPENHIM_TRUST_SELF_SIGNED}
      - MEDIATOR_CONFIG_OPENHIM_AUTH_API_URL=${MFL_MEDIATOR_CONFIG_OPENHIM_AUTH_API_URL}
      - MEDIATOR_CONFIG_OPENHIM_AUTH_REJECT_UNAUTHORIZED=${MFL_MEDIATOR_CONFIG_OPENHIM_AUTH_REJECT_UNAUTHORIZED}
      - MEDIATOR_CONFIG_OPENHIM_AUTH_URN=${MFL_MEDIATOR_CONFIG_OPENHIM_AUTH_URN}
      - MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_CORE_HOST=${MFL_MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_CORE_HOST}
      - MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_REGISTER_MEDIATOR_PATH=${MFL_MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_REGISTER_MEDIATOR_PATH}
      - MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_HEARTBEAT_PATH=${MFL_MEDIATOR_CONFIG_MEDIATOR_CORE_OPENHIM_HEARTBEAT_PATH}
      - MEDIATOR_CONFIG_MEDIATOR_CORE_HEARTBEAT_INTERVAL=${MFL_MEDIATOR_CONFIG_MEDIATOR_CORE_HEARTBEAT_INTERVAL}
      - MEDIATOR_CONFIG_MEDIATOR_CORE_IS_HEARTBEAT_DISABLED=${MFL_MEDIATOR_CONFIG_MEDIATOR_CORE_IS_HEARTBEAT_DISABLED}
      - MEDIATOR_CONFIG_MEDIATOR_SETUP_URN=${MFL_MEDIATOR_CONFIG_MEDIATOR_SETUP_URN}
      - MEDIATOR_CONFIG_MEDIATOR_SETUP_VERSION=${MFL_MEDIATOR_CONFIG_MEDIATOR_SETUP_VERSION}
      - MEDIATOR_CONFIG_MEDIATOR_SETUP_NAME=${MFL_MEDIATOR_CONFIG_MEDIATOR_SETUP_NAME}
      - MEDIATOR_CONFIG_MEDIATOR_SETUP_DESCRIPTION=${MFL_MEDIATOR_CONFIG_MEDIATOR_SETUP_DESCRIPTION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  openhim:
    name: openhim_public
    external: true
  default:
  public:
    name: mfl-api_public
    external: true
