version: '3.9'

services:
  hapi_seeder_config:
    image: node:erbium-alpine
    command: sh -c "cd /importer && ls && npm i && ls && node facility-seeder.js"
    configs:
      - target: /importer/package.json
        source: package.json
      - target: /importer/facility-seeder.js
        source: facility-seeder.js
    networks:
      public:
      # postgres:
    deploy:
      replicas: 1
      restart_policy:
        condition: none

networks:
  public:
    name: hapi-fhir_public
    external: true

configs:
  package.json:
    file: ./package.json
    name: package.json-${package_json_DIGEST:?err}
    labels:
      name: hapi-fhir
  facility-seeder.js:
    file: ./facility-seeder.js
    name: facility-seeder.js-${facility_seeder_js_DIGEST:?err}
    labels:
      name: hapi-fhir

