version: "3.8"

services:
  facility-registry-mfl:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: facility-registry-mfl-dev
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
    command: npm run start:dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mfl-dev-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mfl-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
